[package]
name = "quantum"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [workspace]
# members = [
#     "kernel",
#     "lowlevel_lib",
#     "bootloader/src/bios_boot/stage-1",
#     "bootloader/src/bios_boot/stage-2"
# ]

[dependencies]
mbrman = "0.5.2"
fatfs = "0.3.6"
owo-colors = "3.5.0"

# qemu = { version = "0.1.7", features = ["qemu-x86_64", "optimized"] }