[package]
name = "arch"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
bits = {workspace = true}
util = {workspace = true}
arch-macro = {workspace = true}
lldebug = {workspace = true}
