[package]
name = "lldebug"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
lldebug-macro = {workspace = true}
spin = "0.9.8"

[dev-dependencies]
trybuild = "1.0"
