[package]
name = "stage-1"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
quantum_lib = { path = "../../../../lib/lowlevel_lib" }
over-stacked     = { path = "../../../../lib/over-stacked"}
bootloader  = { path = "../../../bootloader" }
quantum_utils = { path = "../../../../lib/quantum_utils" }

[profile.release]
opt-level="z"
lto = true
codegen-units = 1
debug = 0
overflow-checks = false
panic = "abort"
