[package]
name = "hw"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
hw-macro = {workspace = true}

[dev-dependencies]
trybuild = "1.0"
