name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Nightly
      run: rustup override set nightly
    - name: Add Rust SRC
      run: rustup component add rust-src
    - name: Add LLVM Tools Preview 
      run: rustup component add llvm-tools-preview
    - name: Clean
      run: cargo clean
    - name: Build
      run: cargo run noqemu
    - name: Lib Test
      run: cargo run test-libs
